### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Rkallenkoot** [kjantzer/PONIpar#3]
Perhaps it's a good idea to add a new tag/release for packagist.

Since we've changed the classes / namespaces it might be a good idea for a major version increment like 1.0.0 ?

What do you think ? :)

**Comment by kjantzer** [comment]
Seems reasonable – see my comment on #2 first

**Comment by Rkallenkoot** [comment]
Hmm, I don't see a comment in the PR

**Comment by kjantzer** [comment]
Whoops, didn't "submit" the review. Comment should be there now
